blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf import settings
from django.template.context_processors import static
from django.urls import path, include

from posts.views import PostList, index, PostDetail, search

app_name = 'posts'
urlpatterns = [
    path('', PostList.as_view(), name='list'),
    path('index/', index, name='index'),
    path('search/', search, name='search'),
    path('posts/<pk>/', PostDetail.as_view(), name='detail'),
]

posts/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=120)
    text = models.CharField(max_length=1000000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField()
    created = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.text[:200]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # when i delete an user, all posts are deleted
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)

posts/views.py
from django import forms
from django.shortcuts import render, redirect

# Create your views here.
from django.template.defaultfilters import last
from django.urls import reverse
from django.views.generic import ListView, DetailView

from posts.models import Post, Comment


def index(request):
    return render(request, 'index.html', {})

class PostList(ListView):
    model = Post
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['a'] = Post.objects.all().reverse()[0]
        return context

class CommentForm(forms.Form):
    comment = forms.CharField()

class PostDetail(DetailView):
    model = Post

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = Comment(
                author=request.user,
                post=self.get_object(),
                text=comment_form.cleaned_data['comment']
            )
            comment.save()
        else:
            raise Exception
        return redirect(reverse('posts:detail', args=[self.get_object().id]))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

def search(request):
    if request.method == 'GET': #GET!!!
        post_name =  request.GET.get('search') # do some research what it does
        status = []
        try:
            status = Post.objects.filter(title__icontains=post_name) #returns a list
        except:
            pass
        return render(request,"search.html",{"posts": status})
    else:
        return render(request,"search.html",{})

posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
<body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'posts:list' %}">Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'posts:list' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
            {% block content %}
            {% endblock %}
            <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <form name="myform" method="GET" action="{% url 'posts:search' %}">

                                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." name="search" />
                                    <input class="btn btn-primary" id="button-search" type="submit" value="Go!">
                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">a</a></li>
                                        <li><a href="#!">a</a></li>
                                        <li><a href="#!">a</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">a</a></li>
                                        <li><a href="#!">a</a></li>
                                        <li><a href="#!">a</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">Some text</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Footer</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

posts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Home - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Blog</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Welcome to Blog Home!</h1>
                    <p class="lead mb-0">A Bootstrap 5 starter layout for your next blog homepage</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">January 1, 2021</div>
                            <h2 class="card-title">Featured Post Title {{ object_list|last }}</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                            <a class="btn btn-primary" href="#!">Read more →</a>
                        </div>
                    </div>
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2021</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2021</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2021</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2021</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Pagination-->
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

posts/templates/posts/post_detail.html
{% extends "base.html" %}

{% block content %}
    <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-3">
                    <h1 class="fw-bolder">{{ post.title }}</h1>
                </div>
            </div>
            </header>
    <div class="col-lg-8">
        <!-- Featured blog post-->
        <div class="card mb-4">
            <a href="#!"><img class="card-img-top" src="{{ post.image.url }}" alt="..." width=850 height=350/></a>
            <div class="card-body">
                <div class="small text-muted">{{ post.created }}</div>
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-text"> {{ post.text }}</p>
            </div>
        </div>
        <div class="card mb-4">
            {% for comment in post.comment_set.all %}
        <li>
            <strong>
                {{ comment.author }}<br/>
            </strong>
                {{ comment.text }}
        </li>
        {% endfor %}
            

        </div>
        <div class="card mb-4">
            <form action="{% url 'posts:detail' pk=object.id %}" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit"  class="btn btn-primary" value="Comment">
            </form>

        </div>
    </div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "base.html" %}
        <!-- Page content-->
        {% block content %}
            <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Welcome to Blog Home!</h1>

                </div>
            </div>
            </header>
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="{{ a.image.url }}" alt="..." width=850 height=350/></a>
                        <div class="card-body">
                            <div class="small text-muted">{{ a.created }}</div>
                            <h2 class="card-title">{{ a.title }}</h2>
                            <p class="card-text"> {{ a }}</p>
                            <a class="btn btn-primary" href="{{ a.get_absolute_url }}">Read more →</a>
                        </div>
                    </div>
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        {% for object in object_list %}
                            <div class="col-lg-6">
                                     <div class="card mb-4">
                                        <a href="#!"><img class="card-img-top" src="{{ object.image.url }}" alt="..." width=700 height=350/></a>
                                        <div class="card-body">
                                            <div class="small text-muted">{{ object.created}}</div>
                                            <h2 class="card-title h4">{{ object.title }}</h2>
                                            <p class="card-text">{{ object }}</p>
                                            <a class="btn btn-primary" href="{{ object.get_absolute_url }}">Read more →</a>
                                        </div>
                                     </div>
                            </div>
                        {% endfor %}
                    </div>
{#                    <!-- Pagination-->#}
{#                    <nav aria-label="Pagination">#}
{#                        <hr class="my-0" />#}
{#                        <ul class="pagination justify-content-center my-4">#}
{#                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>#}
{#                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>#}
{#                            {% if object_list|length > 4 %}#}
{#                                <li class="page-item"><a class="page-link" href="#!">2</a></li>#}
{#                            {% endif %}#}
{#                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>#}
{#                        </ul>#}
{#                    </nav>#}
                </div>
        {% endblock %}

posts/templates/search.html
{% extends 'base.html' %}
{% block content %}
    <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-3">
                    <h1 class="fw-bolder">
                        {% if posts %}
                            Result of your search:
                            {% else %}
                            I can't find anything!
                        {% endif %}
                    </h1>
                </div>
            </div>
            </header>
    <div class="col-lg-8">
        {% if posts %}
            <div class="row">
                        {% for object in posts %}
                            <div class="col-lg-6">
                                     <div class="card mb-4">
                                        <a href="#!"><img class="card-img-top" src="{{ object.image.url }}" alt="..." width=700 height=350/></a>
                                        <div class="card-body">
                                            <div class="small text-muted">{{ object.created}}</div>
                                            <h2 class="card-title h4">{{ object.title }}</h2>
                                            <p class="card-text">{{ object }}</p>
                                            <a class="btn btn-primary" href="{{ object.get_absolute_url }}">Read more →</a>
                                        </div>
                                     </div>
                            </div>
                        {% endfor %}
                    </div>
        {% endif %}
    </div>
{% endblock %}